version: '3.7'

services:
  db:
    image: postgres:15.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: db01
      POSTGRES_INITDB_ARGS: "-A md5"
    # ports:
    #   - ${PORT_DB}:${PORT_DB}

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - myapp:/data
    # ports:
    #   - ${PORT_MINIO}:${PORT_MINIO}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data
  
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    # ports:
    #   - ${PORT_RABBITMQ}:${PORT_RABBITMQ}

  manager:
    build: manager/
    container_name: manager
    command: python main.py
    restart: unless-stopped
    depends_on:
      - db
      - rabbitmq
      - minio
    ports:
      - ${PORT_APP}:${PORT_APP}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - DSN_POSTGRE=${DSN_POSTGRE}
      - ENDPOINT_MINIO=${ENDPOINT_MINIO}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - HOST=${HOST}
      - PORT_APP=${PORT_APP}
      - PORT_RABBITMQ=${PORT_RABBITMQ}


  converter:
    build: converter/
    container_name: converter
    restart: unless-stopped
    command: python main.py
    depends_on:
      - db
      - rabbitmq
      - minio
      - manager
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - DSN_POSTGRE=${DSN_POSTGRE}
      - ENDPOINT_MINIO=${ENDPOINT_MINIO}
      - HOST_RABBITMQ=${HOST_RABBITMQ}
      - HOST=${HOST}
      - PORT_RABBITMQ=${PORT_RABBITMQ}

volumes:
  myapp:
