version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=adminadminadmin
      - MINIO_ROOT_PASSWORD=rootrootroot
    command: server /data
